/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import DTO.BaiHat;
import DTO.LoaiNhacDTO;
import ENTITY.Loainhac;
import BUS.LoaiNhacBUS;
import java.util.ArrayList;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Quoc Dat
 */
public class frmQLNhac extends javax.swing.JFrame {

    ArrayList<LoaiNhacDTO> arrLN = new ArrayList<>();
    EntityManager entityManager;
    LoaiNhacBUS lnBUS = new LoaiNhacBUS();
    DefaultListModel jListModel = new DefaultListModel();
    
    /**
     * Creates new form frmQLNhac
     */
    public frmQLNhac() {
        initComponents();
        inItData();
        upDate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlLoaiBH = new javax.swing.JList();
        bntXoaLN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtThemLN = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMaBH = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTenBH = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        arLoiBH = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        rdBQCo = new javax.swing.JRadioButton();
        rdBQKhong = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlLoaiBH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlLoaiBHMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jlLoaiBH);

        bntXoaLN.setBackground(new java.awt.Color(0, 0, 204));
        bntXoaLN.setForeground(new java.awt.Color(240, 240, 240));
        bntXoaLN.setText("Xoá");
        bntXoaLN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntXoaLNActionPerformed(evt);
            }
        });

        jLabel1.setText("Thêm Nhạc");

        jButton2.setText("Thêm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Loại Bài Hát: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtThemLN)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton2)))
                    .addComponent(bntXoaLN, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bntXoaLN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtThemLN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("Bài Hát:");

        jLabel4.setText("Mã: ");

        jLabel5.setText("Tên: ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã", "Tên", "Lyric", "Bản Quyền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        arLoiBH.setColumns(20);
        arLoiBH.setRows(5);
        jScrollPane3.setViewportView(arLoiBH);

        jLabel6.setText("Bản quyền sử dung:");

        buttonGroup1.add(rdBQCo);
        rdBQCo.setSelected(true);
        rdBQCo.setText("Có");

        buttonGroup1.add(rdBQKhong);
        rdBQKhong.setText("Không");

        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 153));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Xoá");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMaBH, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTenBH))
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(rdBQCo)
                        .addGap(18, 18, 18)
                        .addComponent(rdBQKhong)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMaBH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtTenBH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rdBQCo)
                    .addComponent(rdBQKhong)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        LoaiNhacDTO ln = lnBUS.addLNBUS(txtThemLN.getText());
        if(ln!=null){
            arrLN.add(ln);
            upDate();
        }            
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bntXoaLNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntXoaLNActionPerformed
        // TODO add your handling code here:
        LoaiNhacDTO ln = lnBUS.xoaLNBUS((String) jlLoaiBH.getSelectedValue());
        if(ln!=null){
            int i=0;
            while (i<arrLN.size()) {                
                if(arrLN.get(i).getId()==ln.getId()){
                    arrLN.remove(arrLN.get(i));                   
                }
                i++;
            }                         
//            arrLN.remove(jlLoaiBH.getSelectedIndex());
        }
        upDate();
    }//GEN-LAST:event_bntXoaLNActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        BaiHat bh = new BaiHat(Integer.parseInt(txtMaBH.getText()), txtTenBH.getText(),arLoiBH.getText(), rdBQCo.isSelected());
        LoaiNhacDTO ln = lnBUS.getDichVuByNameBUS((String) jlLoaiBH.getSelectedValue());
        if(ln!=null){
            int i=0;
            while (i<arrLN.size()) {                
                if(arrLN.get(i).getId()==ln.getId()){
                    if(!checkBaiHatByName(arrLN.get(i), Integer.parseInt(txtMaBH.getText()))){
                        arrLN.get(i).getArrBaiHat().add(bh);
                        showTB(arrLN.get(i));
                    }else
                        JOptionPane.showMessageDialog(null, "Mã bị Trùng");
                }
                i++;
            }                                   
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jlLoaiBHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlLoaiBHMouseClicked
        // TODO add your handling code here:
        LoaiNhacDTO ln = lnBUS.getDichVuByNameBUS((String) jlLoaiBH.getSelectedValue());
        if(ln!=null){
            int i=0;
            while (i<arrLN.size()) {                
                if(arrLN.get(i).getId()==ln.getId()){                    
                    showTB(arrLN.get(i));
                }
                i++;
            }                                   
        }
    }//GEN-LAST:event_jlLoaiBHMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String selTB =(String) jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 1);
        BaiHat bh = new BaiHat(Integer.parseInt(txtMaBH.getText()), txtTenBH.getText(),arLoiBH.getText(), rdBQCo.isSelected());
        LoaiNhacDTO ln = lnBUS.getDichVuByNameBUS((String) jlLoaiBH.getSelectedValue());
        if(ln!=null){
            int i=0;
            while (i<arrLN.size()) {                
                if(arrLN.get(i).getId()==ln.getId()){
                    int j =0;
                    boolean k=true;
                    while(k) {                
                        if(arrLN.get(i).getArrBaiHat().get(j).getName()==selTB){
                            arrLN.get(i).getArrBaiHat().remove(arrLN.get(i).getArrBaiHat().get(j));
                            k=false;
                        }                       
                        j++;
                    }
                    showTB(arrLN.get(i));
                }
                i++;
            }                                   
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed
    private void showTB(LoaiNhacDTO ln){
        DefaultTableModel tableMode = (DefaultTableModel) jTable1.getModel();
        tableMode.setRowCount(0);
        for(BaiHat bh:ln.getArrBaiHat()){                                 
            tableMode.addRow(new Object[]{bh.getId(),bh.getName(),bh.getLyric(),bh.isBanQuyen()});
        }
    }
    public boolean checkBaiHatByName(LoaiNhacDTO ln,int id){      
        for(BaiHat bh:ln.getArrBaiHat()){         
            if(bh.getId()==(id)){
                return true;           
            }
        }
        return false;
    }
    /**
     * @param args the command line arguments
     */
    public void inItData(){
        
        EntityManagerFactory entityManagerFactory = Persistence.createEntityManagerFactory("QLNhacPU");
        entityManager = entityManagerFactory.createEntityManager();
        entityManager.getTransaction().begin();
        ArrayList<Loainhac> listLoaiNhac;
        Query q= entityManager.createNamedQuery("Loainhac.findAll");
        listLoaiNhac = new ArrayList<Loainhac>( q.getResultList());
        for(Loainhac ln:listLoaiNhac){
            LoaiNhacDTO loaiNhacDTO = new LoaiNhacDTO(ln.getId(),ln.getName());
            arrLN.add(loaiNhacDTO);            
        }
        entityManager.close();      
    
    }   
    public void upDate(){
        jListModel.clear();
        for(LoaiNhacDTO ln:arrLN)
            jListModel.addElement(ln.getName());
        jlLoaiBH.setModel(jListModel);
            
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmQLNhac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmQLNhac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmQLNhac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmQLNhac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmQLNhac().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea arLoiBH;
    private javax.swing.JButton bntXoaLN;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JList jlLoaiBH;
    private javax.swing.JRadioButton rdBQCo;
    private javax.swing.JRadioButton rdBQKhong;
    private javax.swing.JTextField txtMaBH;
    private javax.swing.JTextField txtTenBH;
    private javax.swing.JTextField txtThemLN;
    // End of variables declaration//GEN-END:variables
}
